//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by JunHyeok Lee on 3/4/24.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "TuistMock",
    projects: ["Projects/**"],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)
